---
# Handlers for K3s node maintenance role

# Service restart handlers with proper node type detection
- name: Restart k3s master service
  become: true
  ansible.builtin.systemd:
    name: k3s
    state: restarted
    enabled: true
  when: "'k3s_masters' in group_names"
  listen: "restart k3s service"

- name: Restart k3s worker service
  become: true
  ansible.builtin.systemd:
    name: k3s-node
    state: restarted
    enabled: true
  when: "'k3s_workers' in group_names"
  listen: "restart k3s service"

# Reload systemd daemon if needed
- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
