---
# Variables specific to Debian/Ubuntu systems
k3s_node_maintenance_apt_cache_valid_time: 3600

# Package update behaviour
k3s_node_maintenance_update_cache_retries: 3
k3s_node_maintenance_update_cache_delay: 10
