---
# Debian/Ubuntu package updates
- name: Update package cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ k3s_node_maintenance_apt_cache_valid_time }}"
  tags: [packages, updates, debian, cache]

- name: List upgradable packages
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    apt list --upgradable 2>/dev/null | tail -n +2
  register: k3s_node_maintenance_apt_upgrade_list
  changed_when: false
  tags: [packages, updates, debian, list]

- name: Parse package list
  ansible.builtin.set_fact:
    k3s_node_maintenance_apt_packages_to_upgrade: >-
      {{ k3s_node_maintenance_apt_upgrade_list.stdout_lines | map('regex_replace', '/.*$', '') | list }}
  when: k3s_node_maintenance_apt_upgrade_list.stdout_lines | length > 0
  tags: [packages, updates, debian, parse]

- name: "Upgrading packages: {{ k3s_node_maintenance_apt_packages_to_upgrade | length }}"
  become: true
  ansible.builtin.apt:
    upgrade: dist
  register: k3s_node_maintenance_apt_upgrade_result
  when:
    - k3s_node_maintenance_apt_packages_to_upgrade is defined
    - k3s_node_maintenance_apt_packages_to_upgrade | length > 0
  tags: [packages, updates, debian, upgrade]

- name: Check reboot requirement
  become: true
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: k3s_node_maintenance_apt_reboot_required
  tags: [packages, updates, debian, reboot_check]
