---
# Final cluster health validation
- name: Wait for all nodes to be Ready
  delegate_to: localhost
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300
  tags: [validation, cluster_health, final]

- name: Validate cluster health
  delegate_to: localhost
  block:
    - name: Get all nodes status
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Node
      register: all_nodes

    - name: Set cluster health facts
      set_fact:
        ready_nodes: |
          {%- set ready_count = namespace(value=0) -%}
          {%- for node in all_nodes.resources -%}
            {%- for condition in node.status.conditions | default([]) -%}
              {%- if condition.type == "Ready" and condition.status == "True" -%}
                {%- set ready_count.value = ready_count.value + 1 -%}
              {%- endif -%}
            {%- endfor -%}
          {%- endfor -%}
          {{- ready_count.value -}}
        total_nodes: "{{ all_nodes.resources | length }}"
        schedulable_nodes: "{{ all_nodes.resources | rejectattr('spec.unschedulable', 'defined') | list | length }}"

    - name: Validate cluster health
      assert:
        that:
          - ready_nodes | int == total_nodes | int
          - schedulable_nodes | int >= (total_nodes | int - 1)
        fail_msg: "❌ Cluster validation failed - Ready: {{ ready_nodes }}/{{ total_nodes }}"
        success_msg: "✅ Maintenance complete - {{ inventory_hostname }} updated successfully"

  tags: [validation, cluster_health, final]
