---
# Main task file for K3s node maintenance role
- name: Include prerequisite checks
  ansible.builtin.include_tasks: prerequisites.yml
  tags: [always, prerequisites]

- name: Cluster stability check
  delegate_to: localhost
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 120
  tags: [always, stability]

- name: Include package update checks
  ansible.builtin.include_tasks: package_checks.yml
  tags: [packages, check_updates]

- name: Include Longhorn health validation (pre-maintenance)
  ansible.builtin.include_tasks: longhorn_validation.yml
  tags: [longhorn, health, pre_check]

- name: Include cluster preparation
  ansible.builtin.include_tasks: cluster_preparation.yml
  tags: [cluster, prepare]

- name: Include package updates
  ansible.builtin.include_tasks: package_updates.yml
  tags: [packages, updates]

- name: Include reboot handling
  ansible.builtin.include_tasks: reboot_handling.yml
  tags: [reboot]

- name: Include cluster restoration
  ansible.builtin.include_tasks: cluster_restoration.yml
  tags: [restore]

- name: Include Longhorn health validation (post-maintenance)
  ansible.builtin.include_tasks: longhorn_validation.yml
  tags: [longhorn, health, post_check]

- name: Include final cluster validation
  ansible.builtin.include_tasks: final_validation.yml
  tags: [validation, final]

# Resume task for manual recovery after reboot issues
# Only runs when explicitly called with --tags resume
- name: Resume after reboot (manual recovery)
  ansible.builtin.include_tasks: resume_after_reboot.yml
  tags: [resume]
  when: "'resume' in ansible_run_tags"
