---
# Package update tasks for both Debian and RedHat families
- name: "📦 Applying package updates"
  debug:
    msg: "Processing {{ ansible_facts['os_family'] }} package updates"
  tags: [packages, updates]

- name: Include Debian package updates
  include_tasks: debian_updates.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags: [packages, updates, debian]

- name: Include RedHat package updates
  include_tasks: redhat_updates.yml
  when: ansible_facts['os_family'] == 'RedHat'
  tags: [packages, updates, redhat]

- name: Determine if reboot is required
  set_fact:
    reboot_required: >-
      {{
        (ansible_facts['os_family'] == 'Debian'
          and apt_upgrade_result is defined
          and apt_upgrade_result.changed
          and apt_reboot_required.stat is defined
          and apt_reboot_required.stat.exists)
        or
        (ansible_facts['os_family'] == 'RedHat'
          and dnf_upgrade_result is defined
          and dnf_upgrade_result.changed
          and dnf_reboot_required is defined
          and dnf_reboot_required.stdout is defined
          and dnf_reboot_required.stdout == 'Yes')
      }}
  tags: [packages, updates, reboot_check]
