---
# Package update tasks for both Debian and RedHat families
- name: Applying package updates
  ansible.builtin.debug:
    msg: "Processing {{ ansible_facts['os_family'] }} package updates"
  tags: [packages, updates]

- name: Include Debian package updates
  ansible.builtin.include_tasks: debian_updates.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags: [packages, updates, debian]

- name: Include RedHat package updates
  ansible.builtin.include_tasks: redhat_updates.yml
  when: ansible_facts['os_family'] == 'RedHat'
  tags: [packages, updates, redhat]

- name: Determine if reboot is required
  ansible.builtin.set_fact:
    k3s_node_maintenance_reboot_required: >-
      {{
        (ansible_facts['os_family'] == 'Debian'
          and k3s_node_maintenance_apt_upgrade_result is defined
          and k3s_node_maintenance_apt_upgrade_result.changed
          and k3s_node_maintenance_apt_reboot_required.stat is defined
          and k3s_node_maintenance_apt_reboot_required.stat.exists)
        or
        (ansible_facts['os_family'] == 'RedHat'
          and k3s_node_maintenance_dnf_upgrade_result is defined
          and k3s_node_maintenance_dnf_upgrade_result.changed
          and k3s_node_maintenance_dnf_reboot_required is defined
          and k3s_node_maintenance_dnf_reboot_required.stdout is defined
          and k3s_node_maintenance_dnf_reboot_required.stdout == 'Yes')
      }}
  tags: [packages, updates, reboot_check]
