---
# Prerequisites and pre-flight checks
- name: Gather OS family facts
  setup:
    gather_subset:
      - 'os_family'
  tags: [always, prerequisites, setup]

- name: Validate maintenance prerequisites
  delegate_to: localhost
  ansible.builtin.shell: |
    # Check kubernetes.core collection
    if ! ansible-galaxy collection list | grep -q kubernetes.core; then
      echo "❌ Missing kubernetes.core collection"
      exit 1
    fi
    
    # Check kubectl
    if ! command -v kubectl >/dev/null; then
      echo "❌ kubectl not found on localhost"
      exit 1
    fi
    
    echo "✅ Prerequisites validated"
  register: prereq_check
  failed_when: prereq_check.rc != 0
  tags: [prerequisites]

- name: Check target node tools
  become: true
  shell: |
    os_family="{{ ansible_facts['os_family'] }}"
    if [ "$os_family" = "RedHat" ] && ! command -v dnf >/dev/null; then
      echo "❌ dnf not available"
      exit 1
    elif [ "$os_family" = "Debian" ] && ! command -v apt-get >/dev/null; then
      echo "❌ apt-get not available"
      exit 1
    fi
    echo "✅ Tools available ($os_family)"
  register: tools_check
  failed_when: tools_check.rc != 0
  tags: [prerequisites]
