---
# Reboot handling and waiting for node readiness
- name: "Rebooting node: {{ inventory_hostname }}"
  become: true
  ansible.builtin.reboot:
    reboot_timeout: "{{ k3s_node_maintenance_wait_timeout }}"
    connect_timeout: 5
    test_command: uptime
  when: k3s_node_maintenance_reboot_required
  tags: [reboot, reboot_server]

- name: Stabilisation wait
  delegate_to: localhost
  ansible.builtin.pause:
    seconds: 30
  when: k3s_node_maintenance_reboot_required
  tags: [reboot, reboot_wait]

- name: Node ready check
  delegate_to: localhost
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    name: "{{ inventory_hostname }}"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: "{{ k3s_node_maintenance_wait_timeout }}"
  when: k3s_node_maintenance_reboot_required
  tags: [reboot, reboot_ready, restore]
