---
# RedHat/CentOS package updates
- name: Parse package list
  set_fact:
    dnf_packages_to_upgrade: >-
      {{ dnf_updates_available.results | map(attribute='name') | list }}
  when: dnf_updates_available.results | length > 0
  tags: [packages, updates, redhat, parse]

- name: "⚡ Upgrading {{ dnf_packages_to_upgrade | length }} packages"
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  register: dnf_upgrade_result
  when:
    - dnf_packages_to_upgrade is defined
    - dnf_packages_to_upgrade | length > 0
  tags: [packages, updates, redhat, upgrade]

- name: Check reboot requirement
  become: true
  shell: |
    if command -v needs-restarting >/dev/null 2>&1; then
        needs-restarting -r >/dev/null 2>&1
        if [ $? -eq 0 ]; then
            echo "No"
        else
            echo "Yes"
        fi
    else
        if [ "{{ dnf_upgrade_result.changed | default(false) }}" = "True" ]; then
            echo "{{ dnf_packages_to_upgrade | default([]) | join(' ') }}" | \
              grep -q -E "(kernel|systemd|linux-firmware|glibc)" && echo "Yes" || echo "No"
        else
            echo "No"
        fi
    fi
  register: dnf_reboot_required
  changed_when: false
  check_mode: no
  when: ansible_facts['os_family'] == 'RedHat'
  tags: [packages, updates, redhat, reboot_check]
