---
# Variables specific to K3s worker nodes
k3s_node_maintenance_node_type: "worker"
k3s_node_maintenance_critical_node: false

# Workers can be handled more aggressively
k3s_node_maintenance_drain_timeout: 300  # Standard timeout
k3s_node_maintenance_wait_timeout: 600   # Standard wait time

# Quicker operations for workers
k3s_node_maintenance_reboot_pause: 45    # Longer pause to ensure reboot initiates
